//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armes_magique
    {
        public int Id_weap { get; set; }
        public int Id_weapon { get; set; }
        public Nullable<int> precision { get; set; }
        public int puissance { get; set; }
        public int manacost { get; set; }
        public double range { get; set; }
        public int critique { get; set; }
        public double critmult { get; set; }
        public string spells { get; set; }
        public string type { get; set; }
        public int staminacost { get; set; }
    
        public virtual Weapon_type Weapon_type { get; set; }
        public virtual Weaponry Weaponry { get; set; }
    }
}
