//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Armory()
        {
            this.ElemResArmorAssoc = new HashSet<ElemResArmorAssoc>();
        }
    
        public int Id { get; set; }
        public int Id_armor { get; set; }
        public double atk { get; set; }
        public double def { get; set; }
        public double puissance { get; set; }
        public double resistance { get; set; }
        public double dex_malus { get; set; }
        public double vit_malus { get; set; }
        public int durabilite { get; set; }
        public string categorie { get; set; }
        public string piece { get; set; }
        public bool enchantable { get; set; }
        public string enchantement { get; set; }
        public string capacites { get; set; }
    
        public virtual Armor_cat Armor_cat { get; set; }
        public virtual Items Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElemResArmorAssoc> ElemResArmorAssoc { get; set; }
        public virtual Piece Piece1 { get; set; }
    }
}
