//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beast_Specs
    {
        public int Id_beast { get; set; }
        public double taille_moyenne { get; set; }
        public double masse_moyenne { get; set; }
        public int esperance_de_vie { get; set; }
        public int enfant { get; set; }
        public int jeune { get; set; }
        public int adulte { get; set; }
        public int mur { get; set; }
        public int grand_age { get; set; }
        public int venerable { get; set; }
        public int maximum { get; set; }
    
        public virtual Bestiaire_Beast Bestiaire_Beast { get; set; }
    }
}
