//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combo
    {
        public int Id { get; set; }
        public string nom { get; set; }
        public double attaque { get; set; }
        public Nullable<double> puissance { get; set; }
        public string type { get; set; }
        public int stamina_cout { get; set; }
        public Nullable<int> mana_cout { get; set; }
        public string stat { get; set; }
        public int niveau { get; set; }
        public string Cc { get; set; }
        public Nullable<int> Cc_chance { get; set; }
        public Nullable<double> Cc_duree { get; set; }
        public string buff { get; set; }
        public Nullable<int> buff_chance { get; set; }
        public Nullable<double> buff_duree { get; set; }
        public string etat { get; set; }
        public Nullable<int> etat_chance { get; set; }
        public Nullable<double> etat_duree { get; set; }
        public string ciblage { get; set; }
        public int portee { get; set; }
        public int rayon { get; set; }
        public string weapons { get; set; }
        public string magie_use { get; set; }
        public Nullable<int> lvl_use { get; set; }
        public double cooldown { get; set; }
        public string descr { get; set; }
    
        public virtual Buff Buff1 { get; set; }
        public virtual Ciblage Ciblage1 { get; set; }
        public virtual ComboCat ComboCat { get; set; }
        public virtual Crowd_control Crowd_control { get; set; }
        public virtual Etat Etat1 { get; set; }
        public virtual Stat Stat1 { get; set; }
    }
}
