//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consommables
    {
        public int Id { get; set; }
        public int id_conso { get; set; }
        public string type { get; set; }
        public int n_uses { get; set; }
        public int modulo_1 { get; set; }
        public Nullable<int> modulo_2 { get; set; }
        public int minimum_1 { get; set; }
        public Nullable<int> minimum_2 { get; set; }
        public double duree1 { get; set; }
        public Nullable<double> duree2 { get; set; }
        public string effet_1 { get; set; }
        public string effet_2 { get; set; }
    
        public virtual Conso_type Conso_type { get; set; }
        public virtual Items Items { get; set; }
        public virtual Effets Effets { get; set; }
        public virtual Effets Effets1 { get; set; }
    }
}
