//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conteneurs
    {
        public int Id_contain { get; set; }
        public int Id { get; set; }
        public double taille { get; set; }
        public bool rempli { get; set; }
        public string max_sizeContain { get; set; }
        public bool cumul { get; set; }
    
        public virtual Tailles Tailles { get; set; }
        public virtual Items Items { get; set; }
    }
}
