//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Divinite
    {
        public int Id { get; set; }
        public string nom { get; set; }
        public string surnom { get; set; }
        public Nullable<int> pantheon { get; set; }
        public string sous_domaine { get; set; }
        public string alignement { get; set; }
        public string background { get; set; }
        public string symbole { get; set; }
        public string importance { get; set; }
        public string cultistes { get; set; }
        public string temples { get; set; }
    
        public virtual Alignement Alignement1 { get; set; }
        public virtual Pantheon Pantheon1 { get; set; }
    }
}
