//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enchantements
    {
        public int Id { get; set; }
        public string nom { get; set; }
        public string effet { get; set; }
        public int puissance { get; set; }
        public string element { get; set; }
    
        public virtual Enchant_Effets Enchant_Effets { get; set; }
    }
}
