//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int Id { get; set; }
        public string nom { get; set; }
        public Nullable<decimal> prix_tech { get; set; }
        public Nullable<decimal> prix_mago { get; set; }
        public double masse { get; set; }
        public bool craftable { get; set; }
        public string obtention { get; set; }
        public string origine { get; set; }
        public string taille_cat { get; set; }
        public bool resizable { get; set; }
        public bool storable { get; set; }
        public string recette { get; set; }
        public string description { get; set; }
    
        public virtual Alliage Alliage { get; set; }
        public virtual Bijoux Bijoux { get; set; }
        public virtual Conteneurs Conteneurs { get; set; }
        public virtual Loot Loot { get; set; }
        public virtual Mineraux Mineraux { get; set; }
        public virtual Munition Munition { get; set; }
        public virtual Parchemins Parchemins { get; set; }
        public virtual Tailles Tailles { get; set; }
        public virtual Vehicule Vehicule { get; set; }
        public virtual Armory Armory { get; set; }
        public virtual Consommables Consommables { get; set; }
        public virtual Weaponry Weaponry { get; set; }
        public virtual Livre Livre { get; set; }
        public virtual Monde_w Monde_w { get; set; }
    }
}
