//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        public int Id { get; set; }
        public int id_livre { get; set; }
        public string langue { get; set; }
        public string type { get; set; }
        public string magie { get; set; }
        public Nullable<int> raise_mag { get; set; }
        public string weapon { get; set; }
        public Nullable<int> raise_weap { get; set; }
        public string contenu { get; set; }
    
        public virtual Book_type Book_type { get; set; }
        public virtual Idiome Idiome { get; set; }
        public virtual Items Items { get; set; }
        public virtual Magie_type Magie_type { get; set; }
        public virtual Weapon_type Weapon_type { get; set; }
    }
}
