//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RPGEntities15 : DbContext
    {
        public RPGEntities15()
            : base("name=RPGEntities15")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alliage> Alliage { get; set; }
        public virtual DbSet<Arme_distance> Arme_distance { get; set; }
        public virtual DbSet<Armes_cac> Armes_cac { get; set; }
        public virtual DbSet<Armes_magique> Armes_magique { get; set; }
        public virtual DbSet<Armor_cat> Armor_cat { get; set; }
        public virtual DbSet<Best_cat> Best_cat { get; set; }
        public virtual DbSet<Bijoux> Bijoux { get; set; }
        public virtual DbSet<Bijoux_place> Bijoux_place { get; set; }
        public virtual DbSet<Biomes> Biomes { get; set; }
        public virtual DbSet<Boolean> Boolean { get; set; }
        public virtual DbSet<Capacites_armor> Capacites_armor { get; set; }
        public virtual DbSet<Carburant> Carburant { get; set; }
        public virtual DbSet<Categories_monde> Categories_monde { get; set; }
        public virtual DbSet<ChampLex> ChampLex { get; set; }
        public virtual DbSet<Ciblage> Ciblage { get; set; }
        public virtual DbSet<Comportements> Comportements { get; set; }
        public virtual DbSet<Conso_type> Conso_type { get; set; }
        public virtual DbSet<Conteneurs> Conteneurs { get; set; }
        public virtual DbSet<Continent> Continent { get; set; }
        public virtual DbSet<Crowd_control> Crowd_control { get; set; }
        public virtual DbSet<Degat_type> Degat_type { get; set; }
        public virtual DbSet<Effets> Effets { get; set; }
        public virtual DbSet<Enchant_Effets> Enchant_Effets { get; set; }
        public virtual DbSet<Enchantements> Enchantements { get; set; }
        public virtual DbSet<Etat> Etat { get; set; }
        public virtual DbSet<Loot> Loot { get; set; }
        public virtual DbSet<Mag_element> Mag_element { get; set; }
        public virtual DbSet<Magie_type> Magie_type { get; set; }
        public virtual DbSet<Maniabilite> Maniabilite { get; set; }
        public virtual DbSet<Minerai_type> Minerai_type { get; set; }
        public virtual DbSet<Mineraux> Mineraux { get; set; }
        public virtual DbSet<Mode_deplacement> Mode_deplacement { get; set; }
        public virtual DbSet<Monde_w> Monde_w { get; set; }
        public virtual DbSet<Munition> Munition { get; set; }
        public virtual DbSet<Munition_type> Munition_type { get; set; }
        public virtual DbSet<Parchemins> Parchemins { get; set; }
        public virtual DbSet<Peuplade> Peuplade { get; set; }
        public virtual DbSet<Phenomene> Phenomene { get; set; }
        public virtual DbSet<Piece> Piece { get; set; }
        public virtual DbSet<Procede> Procede { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Reload_cat> Reload_cat { get; set; }
        public virtual DbSet<Stat> Stat { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Usage> Usage { get; set; }
        public virtual DbSet<Vehicule> Vehicule { get; set; }
        public virtual DbSet<Ville> Ville { get; set; }
        public virtual DbSet<Ville_type> Ville_type { get; set; }
        public virtual DbSet<Voies> Voies { get; set; }
        public virtual DbSet<Weapon_type> Weapon_type { get; set; }
        public virtual DbSet<Tailles> Tailles { get; set; }
        public virtual DbSet<ComboCat> ComboCat { get; set; }
        public virtual DbSet<Buff> Buff { get; set; }
        public virtual DbSet<Combo> Combo { get; set; }
        public virtual DbSet<Sorts> Sorts { get; set; }
        public virtual DbSet<Capacites_best> Capacites_best { get; set; }
        public virtual DbSet<Beast_cap_Assoc> Beast_cap_Assoc { get; set; }
        public virtual DbSet<Bestiaire_Beast> Bestiaire_Beast { get; set; }
        public virtual DbSet<CatWorldAssoc> CatWorldAssoc { get; set; }
        public virtual DbSet<ChampLexicAssoc> ChampLexicAssoc { get; set; }
        public virtual DbSet<Monde> Monde { get; set; }
        public virtual DbSet<Mots> Mots { get; set; }
        public virtual DbSet<ElemResArmorAssoc> ElemResArmorAssoc { get; set; }
        public virtual DbSet<Beast_elem> Beast_elem { get; set; }
        public virtual DbSet<Beast_elemRes> Beast_elemRes { get; set; }
        public virtual DbSet<Beast_mago> Beast_mago { get; set; }
        public virtual DbSet<Beast_magoRes> Beast_magoRes { get; set; }
        public virtual DbSet<Pers_mago> Pers_mago { get; set; }
        public virtual DbSet<Pers_magoRes> Pers_magoRes { get; set; }
        public virtual DbSet<Perso_elem> Perso_elem { get; set; }
        public virtual DbSet<Perso_elemRes> Perso_elemRes { get; set; }
        public virtual DbSet<PersoCategorie> PersoCategorie { get; set; }
        public virtual DbSet<Race_ElemMaster> Race_ElemMaster { get; set; }
        public virtual DbSet<Race_Stat_Cap> Race_Stat_Cap { get; set; }
        public virtual DbSet<Races> Races { get; set; }
        public virtual DbSet<Trais> Trais { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Armory> Armory { get; set; }
        public virtual DbSet<Consommables> Consommables { get; set; }
        public virtual DbSet<Idiome> Idiome { get; set; }
        public virtual DbSet<Weaponry> Weaponry { get; set; }
        public virtual DbSet<Book_type> Book_type { get; set; }
        public virtual DbSet<Livre> Livre { get; set; }
        public virtual DbSet<Perso_Creature> Perso_Creature { get; set; }
        public virtual DbSet<Perso_weap_Master> Perso_weap_Master { get; set; }
        public virtual DbSet<Pers_carac> Pers_carac { get; set; }
        public virtual DbSet<Creature_Specs> Creature_Specs { get; set; }
        public virtual DbSet<Race_Specs> Race_Specs { get; set; }
        public virtual DbSet<Beast_Specs> Beast_Specs { get; set; }
        public virtual DbSet<Race_Magie> Race_Magie { get; set; }
        public virtual DbSet<Creature_elem> Creature_elem { get; set; }
        public virtual DbSet<Creature_elemRes> Creature_elemRes { get; set; }
        public virtual DbSet<Creature_mago> Creature_mago { get; set; }
        public virtual DbSet<Creature_magoRes> Creature_magoRes { get; set; }
        public virtual DbSet<Best_stats> Best_stats { get; set; }
        public virtual DbSet<Creature_Stats> Creature_Stats { get; set; }
        public virtual DbSet<Pers_stats> Pers_stats { get; set; }
        public virtual DbSet<Persos> Persos { get; set; }
    }
}
