//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Munition
    {
        public int Id_munition { get; set; }
        public int Id { get; set; }
        public double degats { get; set; }
        public Nullable<double> puissance { get; set; }
        public Nullable<int> mana_cout { get; set; }
        public bool gravite { get; set; }
        public string element_1 { get; set; }
        public Nullable<double> puissance_1 { get; set; }
        public Nullable<int> chance_1 { get; set; }
        public Nullable<int> duree_1 { get; set; }
        public string element_2 { get; set; }
        public Nullable<double> puissance_2 { get; set; }
        public Nullable<int> chance_2 { get; set; }
        public Nullable<int> duree_2 { get; set; }
        public string degats_type { get; set; }
        public string categorie { get; set; }
        public bool enchantable { get; set; }
        public string enchantements { get; set; }
    
        public virtual Mag_element Mag_element { get; set; }
        public virtual Mag_element Mag_element1 { get; set; }
        public virtual Munition_type Munition_type { get; set; }
        public virtual Items Items { get; set; }
    }
}
