//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pantheon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pantheon()
        {
            this.Divinite = new HashSet<Divinite>();
        }
    
        public int Id { get; set; }
        public string nom { get; set; }
        public string domaine { get; set; }
        public string alignement { get; set; }
        public string importance { get; set; }
        public string description { get; set; }
        public string temples { get; set; }
    
        public virtual Alignement Alignement1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Divinite> Divinite { get; set; }
    }
}
