//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicule
    {
        public int Id_vehicule { get; set; }
        public int Id { get; set; }
        public int vitesse_max { get; set; }
        public string maniabilite { get; set; }
        public string carburant { get; set; }
        public string deplacement_mde { get; set; }
        public string accessibilite { get; set; }
        public int solidite { get; set; }
        public int reservoir { get; set; }
    
        public virtual Maniabilite Maniabilite1 { get; set; }
        public virtual Items Items { get; set; }
    }
}
