//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Jahr_words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ville
    {
        public string nom { get; set; }
        public string region { get; set; }
        public string peuplade_principales { get; set; }
        public string type { get; set; }
    
        public virtual Region Region1 { get; set; }
        public virtual Ville_type Ville_type { get; set; }
    }
}
